### ISSUE TITLE
Rainfall Scenario DEP work

### ISSUE THREAD

**Issue by akrherz** [dailyerosion/dep#39]
5 June 2017 meeting with Dr Cruse and Dr Todey to discuss DEP scenario work for modelling changes with precipitation for future climates.

 - precipitation patterns are shifting, but the shifts may be disjointed and hard to generalize
 - gulley erosion is still important with crops at full canopy, so this will be a limitation of what we are doing?
 - The primary output of this work is the loss of water storage in the top soil
 - [x] model from -20% to +20% arbitrary increases in precipitation
 - [x] model from -14 to 14 day shift in precipitation
 - some sort of seasonal up/down shifting with some portion of summer precip being moved to other seasons
 - [x] arbitrary addition of an amount of precipitation during the spring season
 - [x] model -20% to +20% increases in intensity with total precipitation unchanged.

**Comment by akrherz** [comment]
Yikes, my scenario data table from yesterday is now missing from this ticket.

Scenario | Multiplier | Status
-- | -- | --
49 | 0.80 | -
50 | 0.84 | -
51 | 0.88 | -
52 | 0.92 | -
53 | 0.96 | -
54 | 1.04 | -
55 | 1.08 | -
56 | 1.12 | -
57 | 1.16 | -
58 | 1.20 | -

**Comment by akrherz** [comment]
Attempted to run a scenario today, but the multiplier tool was slow slow slow and hit a bug with a bad breakpoint :/
```
Traceback (most recent call last):
  File "arb_precip_delta.py", line 57, in <module>
    main(sys.argv)
  File "arb_precip_delta.py", line 52, in main
    for _ in tqdm(pool.imap_unordered(_editor, finder())):
  File "/opt/miniconda3/envs/prod/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/opt/miniconda3/envs/prod/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
  File "/opt/miniconda3/envs/prod/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "arb_precip_delta.py", line 51, in _editor
    editor(fn, scenario, multiplier)
  File "arb_precip_delta.py", line 28, in editor
    fp.write("%s %.2f\n" % (tokens[0], float(tokens[1]) * multiplier))
ValueError: could not convert string to float: '2.396.5'
```

will fix this and try again tomorrow.

**Comment by akrherz** [comment]
Augh, back to the drawing board.  The runfile generator had a bug and was always providing the baseline file.

**Comment by akrherz** [comment]
OK, we are back in business on this issue now that the full precip reprocessing is done.  Will see what I can foul up this time!

**Comment by akrherz** [comment]
We are back in the saddle on this and am doing the arbitrary day shifting now.

Scenario | Day Shift | Status
--- | --- | ---
102 | Climate -14 Day Shift | 
103 | Climate -13 Day Shift | 
104 | Climate -12 Day Shift | 
105 | Climate -11 Day Shift | 
106 | Climate -10 Day Shift | 
107 | Climate -9 Day Shift | 
108 | Climate -8 Day Shift | 
109 | Climate -7 Day Shift | 
110 | Climate -6 Day Shift | 
111 | Climate -5 Day Shift | 
112 | Climate -4 Day Shift | 
113 | Climate -3 Day Shift | 
114 | Climate -2 Day Shift | 
115 | Climate -1 Day Shift | 
116 | Climate +1 Day Shift | 
117 | Climate +2 Day Shift | 
118 | Climate +3 Day Shift | 
119 | Climate +4 Day Shift | 
120 | Climate +5 Day Shift | 
121 | Climate +6 Day Shift | 
122 | Climate +7 Day Shift | 
123 | Climate +8 Day Shift | 
124 | Climate +9 Day Shift | 
125 | Climate +10 Day Shift | 
126 | Climate +11 Day Shift | 
127 | Climate +12 Day Shift | 
128 | Climate +13 Day Shift | 
129 | Climate +14 Day Shift |

**Comment by akrherz** [comment]
On 18 Dec 2020, I had a call with some folks from U of Minnesota and there are synergies to be had here with their work.  Some additional TODO items.

- [ ] investigate what exactly WEPP's `cligen` can do and the various data formats it will take.
- [ ] Do some more sensitivity runs to my current climate scenarios.

**Comment by akrherz** [comment]
My adding spring storms scenarios

Scenario | Num 1" Storms Per Year | Status
--- | --- | ---
130 | 1 | 
131 | 2 | 
132 | 3 | 
133 | 4 | 
134 | 5 | 
135 | 6 | 
136 | 7 | 
137 | 8 | 
138 | 9 | 
139 | 10 |

**Comment by akrherz** [comment]
I've an implementation of a constant total precip, but change in peak intensity

Scenario | Intensity Change | Run Status
--- | --- | ---
142 | 80% | -
143 | 84% | -
144 | 88% | -
145 | 92% | -
146 | 96% | -
147 | 104% | -
148 | 108% | -
149 | 112% | -
150 | 116% | -
151 | 120% | -

**Comment by akrherz** [comment]
I've seen enough on this issue, closing the book for now and will reopen new tickets for subsequent things.
